-- ÓRGÃO SUPERIOR

CREATE TABLE IF NOT EXISTS ORGAO_SUPERIOR(
	ID_ORGAO_SUPERIOR INTEGER PRIMARY KEY,
	NOME_ORGAO_SUPERIOR VARCHAR(256) NOT NULL,
	EXERCICIO INTEGER NOT NULL
);

-- ÓRGÃO SUBORDINADO

CREATE TABLE IF NOT EXISTS ORGAO_SUBORDINADO(
	ID_ORGAO_SUBORDINADO INTEGER PRIMARY KEY,
	NOME_ORGAO_SUBORDINADO VARCHAR(256) NOT NULL,
	ID_ORGAO_SUPERIOR INTEGER NOT NULL,
	
	FOREIGN KEY (ID_ORGAO_SUPERIOR) REFERENCES ORGAO_SUPERIOR
);

-- UNIDADE ORÇAMENTÁRIA

CREATE TABLE IF NOT EXISTS UNIDADE_ORCAMENTARIA(
	ID_UNIDADE_ORCAMENTARIA INTEGER PRIMARY KEY,
	NOME_UNIDADE_ORCAMENTARIA VARCHAR(256) NOT NULL,
	ID_ORGAO_SUBORDINADO INTEGER NOT NULL,
	
	FOREIGN KEY (ID_ORGAO_SUBORDINADO) REFERENCES ORGAO_SUBORDINADO
);

-- FUNÇÃO

CREATE TABLE IF NOT EXISTS FUNCAO(
	ID_FUNCAO INTEGER PRIMARY KEY,
	NOME_FUNCAO VARCHAR(256) NOT NULL,
	ID_UNIDADE_ORCAMENTARIA INTEGER NOT NULL,
	
	FOREIGN KEY (ID_UNIDADE_ORCAMENTARIA) REFERENCES UNIDADE_ORCAMENTARIA
);

-- SUBFUNÇÃO

CREATE TABLE IF NOT EXISTS SUBFUNCAO(
	ID_SUBFUNCAO INTEGER PRIMARY KEY,
	NOME_SUBFUNCAO VARCHAR(256) NOT NULL,
	ID_FUNCAO INTEGER NOT NULL,
	
	FOREIGN KEY (ID_FUNCAO) REFERENCES FUNCAO
);

-- PROGRAMA ORÇAMENTÁRIO

CREATE TABLE IF NOT EXISTS PROGRAMA_ORCAMENTARIO(
	ID_PROGRAMA_ORCAMENTARIO INTEGER PRIMARY KEY,
	NOME_PROGRAMA_ORCAMENTARIO VARCHAR(256) NOT NULL,
	ID_SUBFUNCAO INTEGER NOT NULL,
	
	FOREIGN KEY (ID_SUBFUNCAO) REFERENCES SUBFUNCAO
);

-- AÇÃO

CREATE TABLE IF NOT EXISTS ACAO(
	ID_ACAO VARCHAR(50) PRIMARY KEY,
	NOME_ACAO VARCHAR(256) NOT NULL,
	ID_PROGRAMA_ORCAMENTARIO INTEGER NOT NULL,
	
	FOREIGN KEY (ID_PROGRAMA_ORCAMENTARIO) REFERENCES PROGRAMA_ORCAMENTARIO
);

-- CATEGORIA ECONÔMICA

CREATE TABLE IF NOT EXISTS CATEGORIA_ECONOMICA(
	ID_CATEGORIA_ECONOMICA INTEGER PRIMARY KEY,
	NOME_CATEGORIA_ECONOMICA VARCHAR(256) NOT NULL,
	ID_ACAO VARCHAR(50) NOT NULL,
	
	FOREIGN KEY (ID_ACAO) REFERENCES ACAO
);

-- GRUPO DESPESA

CREATE TABLE IF NOT EXISTS GRUPO_DESPESA(
	ID_GRUPO_DESPESA INTEGER PRIMARY KEY,
	NOME_GRUPO_DESPESA VARCHAR(256) NOT NULL,
	ID_CATEGORIA_ECONOMICA INTEGER NOT NULL,
	
	FOREIGN KEY (ID_CATEGORIA_ECONOMICA) REFERENCES CATEGORIA_ECONOMICA
);

-- ELEMENTO DESPESA

CREATE TABLE IF NOT EXISTS ELEMENTO_DESPESA(
	ID SERIAL PRIMARY KEY,
	ID_ELEMENTO_DESPESA INTEGER NOT NULL,
	NOME_ELEMENTO_DESPESA VARCHAR(256) NOT NULL,
	ORCAMENTO_INICIAL NUMERIC(16,2) NOT NULL,
	ORCAMENTO_ATUALIZADO NUMERIC(16,2) NOT NULL,
	ORCAMENTO_EMPENHADO NUMERIC(16,2) NOT NULL,
	ORCAMENTO_REALIZADO NUMERIC(16,2) NOT NULL,
	ID_GRUPO_DESPESA INTEGER NOT NULL,
	
	FOREIGN KEY (ID_GRUPO_DESPESA) REFERENCES GRUPO_DESPESA
);