-- Qual órgão superior possui maior valor de despesa realizado?
SELECT ORGAO_SUPERIOR.NOME_ORGAO_SUPERIOR, SUM(ELEMENTO_DESPESA.ORCAMENTO_REALIZADO) FROM ELEMENTO_DESPESA
RIGHT JOIN GRUPO_DESPESA ON GRUPO_DESPESA.ID_GRUPO_DESPESA = ELEMENTO_DESPESA.ID_GRUPO_DESPESA
RIGHT JOIN CATEGORIA_ECONOMICA ON CATEGORIA_ECONOMICA.ID_CATEGORIA_ECONOMICA = GRUPO_DESPESA.ID_CATEGORIA_ECONOMICA
RIGHT JOIN ACAO ON ACAO.ID_ACAO = CATEGORIA_ECONOMICA.ID_ACAO
RIGHT JOIN PROGRAMA_ORCAMENTARIO ON PROGRAMA_ORCAMENTARIO.ID_PROGRAMA_ORCAMENTARIO = ACAO.ID_PROGRAMA_ORCAMENTARIO
RIGHT JOIN SUBFUNCAO ON SUBFUNCAO.ID_SUBFUNCAO = PROGRAMA_ORCAMENTARIO.ID_SUBFUNCAO
RIGHT JOIN FUNCAO ON FUNCAO.ID_FUNCAO = SUBFUNCAO.ID_FUNCAO
RIGHT JOIN UNIDADE_ORCAMENTARIA ON UNIDADE_ORCAMENTARIA.ID_UNIDADE_ORCAMENTARIA = FUNCAO.ID_UNIDADE_ORCAMENTARIA
RIGHT JOIN ORGAO_SUBORDINADO ON ORGAO_SUBORDINADO.ID_ORGAO_SUBORDINADO = UNIDADE_ORCAMENTARIA.ID_ORGAO_SUBORDINADO
RIGHT JOIN ORGAO_SUPERIOR ON ORGAO_SUPERIOR.ID_ORGAO_SUPERIOR = ORGAO_SUBORDINADO.ID_ORGAO_SUPERIOR
GROUP BY (ORGAO_SUPERIOR.NOME_ORGAO_SUPERIOR, ELEMENTO_DESPESA.ORCAMENTO_REALIZADO)
ORDER BY ELEMENTO_DESPESA.ORCAMENTO_REALIZADO DESC;

-- Qual órgão subordinado possui maior valor de despesa realizado?
SELECT ORGAO_SUBORDINADO.NOME_ORGAO_SUBORDINADO, MAX(ELEMENTO_DESPESA.ORCAMENTO_REALIZADO) FROM ELEMENTO_DESPESA
RIGHT JOIN GRUPO_DESPESA ON GRUPO_DESPESA.ID_GRUPO_DESPESA = ELEMENTO_DESPESA.ID_GRUPO_DESPESA
RIGHT JOIN CATEGORIA_ECONOMICA ON CATEGORIA_ECONOMICA.ID_CATEGORIA_ECONOMICA = GRUPO_DESPESA.ID_CATEGORIA_ECONOMICA
RIGHT JOIN ACAO ON ACAO.ID_ACAO = CATEGORIA_ECONOMICA.ID_ACAO
RIGHT JOIN PROGRAMA_ORCAMENTARIO ON PROGRAMA_ORCAMENTARIO.ID_PROGRAMA_ORCAMENTARIO = ACAO.ID_PROGRAMA_ORCAMENTARIO
RIGHT JOIN SUBFUNCAO ON SUBFUNCAO.ID_SUBFUNCAO = PROGRAMA_ORCAMENTARIO.ID_SUBFUNCAO
RIGHT JOIN FUNCAO ON FUNCAO.ID_FUNCAO = SUBFUNCAO.ID_FUNCAO
RIGHT JOIN UNIDADE_ORCAMENTARIA ON UNIDADE_ORCAMENTARIA.ID_UNIDADE_ORCAMENTARIA = FUNCAO.ID_UNIDADE_ORCAMENTARIA
RIGHT JOIN ORGAO_SUBORDINADO ON ORGAO_SUBORDINADO.ID_ORGAO_SUBORDINADO = UNIDADE_ORCAMENTARIA.ID_ORGAO_SUBORDINADO
GROUP BY (ORGAO_SUBORDINADO.NOME_ORGAO_SUBORDINADO, ELEMENTO_DESPESA.ORCAMENTO_REALIZADO)
ORDER BY ELEMENTO_DESPESA.ORCAMENTO_REALIZADO DESC;


-- Qual órgão subordinado possui menor valor de despesa realizado?
SELECT ORGAO_SUBORDINADO.NOME_ORGAO_SUBORDINADO, MIN(ELEMENTO_DESPESA.ORCAMENTO_REALIZADO) FROM ELEMENTO_DESPESA
RIGHT JOIN GRUPO_DESPESA ON GRUPO_DESPESA.ID_GRUPO_DESPESA = ELEMENTO_DESPESA.ID_GRUPO_DESPESA
RIGHT JOIN CATEGORIA_ECONOMICA ON CATEGORIA_ECONOMICA.ID_CATEGORIA_ECONOMICA = GRUPO_DESPESA.ID_CATEGORIA_ECONOMICA
RIGHT JOIN ACAO ON ACAO.ID_ACAO = CATEGORIA_ECONOMICA.ID_ACAO
RIGHT JOIN PROGRAMA_ORCAMENTARIO ON PROGRAMA_ORCAMENTARIO.ID_PROGRAMA_ORCAMENTARIO = ACAO.ID_PROGRAMA_ORCAMENTARIO
RIGHT JOIN SUBFUNCAO ON SUBFUNCAO.ID_SUBFUNCAO = PROGRAMA_ORCAMENTARIO.ID_SUBFUNCAO
RIGHT JOIN FUNCAO ON FUNCAO.ID_FUNCAO = SUBFUNCAO.ID_FUNCAO
RIGHT JOIN UNIDADE_ORCAMENTARIA ON UNIDADE_ORCAMENTARIA.ID_UNIDADE_ORCAMENTARIA = FUNCAO.ID_UNIDADE_ORCAMENTARIA
RIGHT JOIN ORGAO_SUBORDINADO ON ORGAO_SUBORDINADO.ID_ORGAO_SUBORDINADO = UNIDADE_ORCAMENTARIA.ID_ORGAO_SUBORDINADO
GROUP BY (ORGAO_SUBORDINADO.NOME_ORGAO_SUBORDINADO, ELEMENTO_DESPESA.ORCAMENTO_REALIZADO)
ORDER BY ELEMENTO_DESPESA.ORCAMENTO_REALIZADO


-- Qual foi a despesa total realizada da Unipampa no exercício de 2021?
SELECT ORGAO_SUPERIOR.EXERCICIO, ORGAO_SUBORDINADO.NOME_ORGAO_SUBORDINADO, SUM(ELEMENTO_DESPESA.ORCAMENTO_INICIAL),
SUM(ELEMENTO_DESPESA.ORCAMENTO_ATUALIZADO), SUM(ELEMENTO_DESPESA.ORCAMENTO_EMPENHADO), SUM(ELEMENTO_DESPESA.ORCAMENTO_REALIZADO) FROM ELEMENTO_DESPESA
FULL JOIN GRUPO_DESPESA ON GRUPO_DESPESA.ID_GRUPO_DESPESA = ELEMENTO_DESPESA.ID_GRUPO_DESPESA
FULL JOIN CATEGORIA_ECONOMICA ON CATEGORIA_ECONOMICA.ID_CATEGORIA_ECONOMICA = GRUPO_DESPESA.ID_CATEGORIA_ECONOMICA
FULL JOIN ACAO ON ACAO.ID_ACAO = CATEGORIA_ECONOMICA.ID_ACAO
FULL JOIN PROGRAMA_ORCAMENTARIO ON PROGRAMA_ORCAMENTARIO.ID_PROGRAMA_ORCAMENTARIO = ACAO.ID_PROGRAMA_ORCAMENTARIO
FULL JOIN SUBFUNCAO ON SUBFUNCAO.ID_SUBFUNCAO = PROGRAMA_ORCAMENTARIO.ID_SUBFUNCAO
FULL JOIN FUNCAO ON FUNCAO.ID_FUNCAO = SUBFUNCAO.ID_FUNCAO
FULL JOIN UNIDADE_ORCAMENTARIA ON UNIDADE_ORCAMENTARIA.ID_UNIDADE_ORCAMENTARIA = FUNCAO.ID_UNIDADE_ORCAMENTARIA
FULL JOIN ORGAO_SUBORDINADO ON ORGAO_SUBORDINADO.ID_ORGAO_SUBORDINADO = UNIDADE_ORCAMENTARIA.ID_ORGAO_SUBORDINADO
FULL JOIN ORGAO_SUPERIOR ON ORGAO_SUPERIOR.ID_ORGAO_SUPERIOR = ORGAO_SUBORDINADO.ID_ORGAO_SUPERIOR
WHERE ORGAO_SUBORDINADO.NOME_ORGAO_SUBORDINADO ILIKE '%Pampa%'
GROUP BY (ORGAO_SUPERIOR.EXERCICIO, ORGAO_SUBORDINADO.NOME_ORGAO_SUBORDINADO, ELEMENTO_DESPESA.ORCAMENTO_INICIAL);


-- Qual foi a ação da Unipampa que mais dispendeu custos?
SELECT ORGAO_SUBORDINADO.NOME_ORGAO_SUBORDINADO, ACAO.NOME_ACAO, SUM(ELEMENTO_DESPESA.ORCAMENTO_REALIZADO) FROM ELEMENTO_DESPESA
RIGHT JOIN GRUPO_DESPESA ON GRUPO_DESPESA.ID_GRUPO_DESPESA = ELEMENTO_DESPESA.ID_GRUPO_DESPESA
RIGHT JOIN CATEGORIA_ECONOMICA ON CATEGORIA_ECONOMICA.ID_CATEGORIA_ECONOMICA = GRUPO_DESPESA.ID_CATEGORIA_ECONOMICA
RIGHT JOIN ACAO ON ACAO.ID_ACAO = CATEGORIA_ECONOMICA.ID_ACAO
RIGHT JOIN PROGRAMA_ORCAMENTARIO ON PROGRAMA_ORCAMENTARIO.ID_PROGRAMA_ORCAMENTARIO = ACAO.ID_PROGRAMA_ORCAMENTARIO
RIGHT JOIN SUBFUNCAO ON SUBFUNCAO.ID_SUBFUNCAO = PROGRAMA_ORCAMENTARIO.ID_SUBFUNCAO
RIGHT JOIN FUNCAO ON FUNCAO.ID_FUNCAO = SUBFUNCAO.ID_FUNCAO
RIGHT JOIN UNIDADE_ORCAMENTARIA ON UNIDADE_ORCAMENTARIA.ID_UNIDADE_ORCAMENTARIA = FUNCAO.ID_UNIDADE_ORCAMENTARIA
RIGHT JOIN ORGAO_SUBORDINADO ON ORGAO_SUBORDINADO.ID_ORGAO_SUBORDINADO = UNIDADE_ORCAMENTARIA.ID_ORGAO_SUBORDINADO
WHERE ORGAO_SUBORDINADO.NOME_ORGAO_SUBORDINADO ILIKE '%Pampa%'
GROUP BY (ORGAO_SUBORDINADO.NOME_ORGAO_SUBORDINADO, ACAO.NOME_ACAO);